name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      run: |
        # Install Visual Studio Build Tools
        choco install visualstudio2019buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Set up environment variables
      run: |
        # Set up environment variables for Visual Studio Build Tools
        echo "##vso[task.prependpath]C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64"
        echo "##vso[task.prependpath]C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64"

    - name: Build DLL
      run: |
        cd build
        cl.exe /LD CreateUserDLL.cpp /link /OUT:CreateUserDLL.dll netapi32.lib

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v2
      with:
        name: CreateUserDLL
        path: build/CreateUserDLL.dll
