name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW-w64
      run: |
        # Download and install MinGW-w64
        choco install mingw-w64 -y

    - name: Set up environment variables
      run: |
        # Set up environment variables for MinGW-w64
        echo "##vso[task.prependpath]C:\ProgramData\chocolatey\lib\mingw-w64\tools\install\mingw64\bin"

    - name: Build DLL
      run: |
        cd build
        g++ -shared -o CreateUserDLL.dll CreateUserDLL.cpp -lnetapi32

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v2
      with:
        name: CreateUserDLL
        path: build/CreateUserDLL.dll
