name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        # Download and install MinGW
        choco install mingw -y

    - name: Set up environment variables
      run: |
        # Set up environment variables for MinGW
        echo "##vso[task.prependpath]C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"

    - name: Build DLL
      run: |
        cd build
        g++ -shared -o CreateUserDLL.dll CreateUserDLL.cpp -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt" -lnetapi32

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v2
      with:
        name: CreateUserDLL
        path: build/CreateUserDLL.dll
