name: Build C++ Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional" -y

    - name: Build
      run: cl.exe /EHsc /Fe:CreateUser.exe CreateUser.cpp netapi32.lib

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CompiledExecutable
        path: CreateUser.exe
