name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC environment
      uses: actions/setup-msbuild@v1
      with:
        vs-version: 'latest' # 使用最新版本的 Visual Studio

    - name: Build DLL
      run: |
        cd build
        msbuild CreateUserDLL.cpp /p:Configuration=Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v2
      with:
        name: CreateUserDLL
        path: build/Release/CreateUserDLL.dll
