name: Build C++ Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: sudo apt-get install mingw-w64 -y

    - name: Build
      run: i686-w64-mingw32-g++ -o CreateUser.exe CreateUser.cpp -lnetapi32

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CompiledExecutable
        path: CreateUser.exe
