name: Build and Commit Go Program

on:
  push:
    branches:
      - main

jobs:
  build_and_commit:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x # 指定您希望使用的 Go 版本

    - name: Build
      run: go build -o bin/CreateUser.exe CreateUser.go

    - name: Commit changes
      run: |
        git config --global user.name "loyejaotdiqr47123"
        git config --global user.email "bobotwo@sibnet.ru"
        git add bin/CreateUser.exe
        git commit -m "Add compiled executable"
        git push origin main
        echo "Changes committed."

    - name: Authenticate with GITHUB_TOKEN
      run: |
        git config --global user.name "loyejaotdiqr47123"
        git config --global user.email "bobotwo@sibnet.ru"
        git checkout main
        git pull origin main
        echo "Authenticated with GITHUB_TOKEN."

    - name: Push changes with GITHUB_TOKEN
      run: |
        git add bin/CreateUser.exe
        git commit -m "Update compiled executable"
        git push origin main
        echo "Changes pushed with GITHUB_TOKEN."
