name: Build Go Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.8 # 指定您希望使用的 Go 版本

    - name: Build
      run: go build -o CreateUser.exe CreateUser.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CompiledExecutable
        path: CreateUser.exe
